app:
  name: familieband-site
  namespace: borgers
  labels:
    app: familieband-site
    release: familieband-site
    managed-by: helm
  selectorLabels:
    app: familieband-site
  image:
    repository: ghcr.io/lodybo/borgers-familie-site
    tag: v1.9.0
    pullPolicy: IfNotPresent
  domains:
    production: borgersfamilieband.spindraad.app
    development: borgersfamilieband.spindraad.dev
    external: borgersfamilie.nl

environment: production # or: development

resources:
  requests:
    cpu: 50m
    memory: 600Mi
  limits:
    cpu: 200m
    memory: 1.2Gi

service:
  name: familieband-site-service
  port: 80
  targetPort: 3000

postgres:
  database: borgers_familie
  username: borgers_familie
  password: "<PLACEHOLDER>"
  storage:
    size: 1Gi

secrets:
  sessionSecret: "<PLACEHOLDER>"
  sendgridApiKey: "<PLACEHOLDER>"
  csrfSecret: "<PLACEHOLDER>"
  mollieApiKey: "<PLACEHOLDER>"

pvc:
  name: familieband-site-pvc
  replicas: 1
  storageClassName: "do-block-storage"
  accessMode: ReadWriteOnce
  size: 1Gi
