apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-session-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  password: {{ .Values.secrets.sessionSecret | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-sendgrid-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  apiKey: {{ .Values.secrets.sendgridApiKey | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-csrf-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  csrfSecret: {{ .Values.secrets.csrfSecret | b64enc | quote }}
