apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.app.namespace }}
  labels: {{ toYaml .Values.app.labels | nindent 4 }}
    component: app
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: app
