apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-network-policy
  namespace: {{ .Values.app.namespace }}
  labels: {{ toYaml .Values.app.labels | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.app.name }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.app.name }}
              component: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
---
{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: NetworkPolicy*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Values.app.name }}-postgres-network-policy*/}}
{{/*  namespace: {{ .Values.app.namespace }}*/}}
{{/*  labels: {{ toYaml .Values.app.labels | nindent 4 }}*/}}
{{/*    component: postgres*/}}
{{/*spec:*/}}
{{/*  podSelector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: {{ .Values.app.name }}*/}}
{{/*      component: postgres*/}}
{{/*  policyTypes:*/}}
{{/*    - Ingress*/}}
{{/*    - Egress*/}}
{{/*  ingress:*/}}
{{/*    - from:*/}}
{{/*        - podSelector:*/}}
{{/*            matchLabels:*/}}
{{/*              app: {{ .Values.app.name }}*/}}
{{/*      ports:*/}}
{{/*        - protocol: TCP*/}}
{{/*          port: 5432*/}}
{{/*  egress:*/}}
{{/*    - to: []*/}}
{{/*      ports:*/}}
{{/*        - protocol: TCP*/}}
{{/*          port: 53*/}}
{{/*        - protocol: UDP*/}}
{{/*          port: 53*/}}
