apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-postgres
  labels:
    {{ .Values.app.labels | nindent 4 }}
    component: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    {{ .Values.app.selectorLabels | nindent 4 }}
    component: postgres
