apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-postgres-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
    component: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
