apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-postgres-secret
  labels:
    {{ .Values.app.labels | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
